# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '.svg$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# codespell: note that --ignore-words may be read as "allow words"
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    -   id: codespell
        args:
        - --ignore-words=docs/spelling.txt
# Needs install
# include-what-you-use
#-   repo: https://github.com/pocc/pre-commit-hooks
#    rev: v1.3.5
#    hooks:
#    -   id: include-what-you-use
